/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mixamorig1Hips: THREE.Bone
  }
  materials: {}
}

// {/* Instatiating Animation Type? ==================================== */}

type ActionName = 'Armature|mixamo.com|Layer0'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Ape_Animation(props: JSX.IntrinsicElements['group']) {

  // {/* Instatiating Model ==================================== */}
  const group = useRef<any>(null!)
  const { nodes, materials, animations } = useGLTF('/glbFiles/BoredApe_Animations.glb') as unknown as GLTFResult
  const { ref, actions, names } = useAnimations(animations,group)

  // {/* After DOM updates this is called ==================================== */}
  useEffect(() =>
  {
    actions['Armature|mixamo.com|Layer0']?.play()
  }, [] )

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={1}>
          <primitive object={nodes.mixamorig1Hips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/BoredApe_Animations.glb')
