/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Teeth_Wolf3D_head_custom_mesh003mesh001: THREE.SkinnedMesh
    Wolf3D_Body_Custom001_mesh006: THREE.SkinnedMesh
    Wolf3D_EyeLeft_eye_l_Mesh006mesh: THREE.SkinnedMesh
    Wolf3D_EyeRight_eye_r_Mesh004mesh: THREE.SkinnedMesh
    Wolf3D_Head_Custom_Wolf3D_head_custom_mesh003mesh: THREE.SkinnedMesh
    Wolf3D_Outfit_Bottom_Wolf3D_outfit_bottom_mesh009mesh: THREE.SkinnedMesh
    Wolf3D_Outfit_Footwear_Retopo_Wolf3D_outfit_footwear_me_a330ea9: THREE.SkinnedMesh
    Wolf3D_Outfit_Top_Wolf3D_outfit_top_mesh013mesh: THREE.SkinnedMesh
    mixamorigHips: THREE.Bone
  }
  materials: {}
}

type ActionName = 'Armature|mixamo.com|Layer0'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null!)
  const { nodes, materials, animations } = useGLTF('/ScottApe_2-transformed.glb') as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Wolf3D_Teeth_Wolf3D_head_custom_mesh003mesh001" geometry={nodes.Wolf3D_Teeth_Wolf3D_head_custom_mesh003mesh001.geometry} material={nodes.Wolf3D_Teeth_Wolf3D_head_custom_mesh003mesh001.material} skeleton={nodes.Wolf3D_Teeth_Wolf3D_head_custom_mesh003mesh001.skeleton} />
          <skinnedMesh name="Wolf3D_Body_Custom001_mesh006" geometry={nodes.Wolf3D_Body_Custom001_mesh006.geometry} material={nodes.Wolf3D_Body_Custom001_mesh006.material} skeleton={nodes.Wolf3D_Body_Custom001_mesh006.skeleton} />
          <skinnedMesh name="Wolf3D_EyeLeft_eye_l_Mesh006mesh" geometry={nodes.Wolf3D_EyeLeft_eye_l_Mesh006mesh.geometry} material={nodes.Wolf3D_EyeLeft_eye_l_Mesh006mesh.material} skeleton={nodes.Wolf3D_EyeLeft_eye_l_Mesh006mesh.skeleton} />
          <skinnedMesh name="Wolf3D_EyeRight_eye_r_Mesh004mesh" geometry={nodes.Wolf3D_EyeRight_eye_r_Mesh004mesh.geometry} material={nodes.Wolf3D_EyeRight_eye_r_Mesh004mesh.material} skeleton={nodes.Wolf3D_EyeRight_eye_r_Mesh004mesh.skeleton} />
          <skinnedMesh name="Wolf3D_Head_Custom_Wolf3D_head_custom_mesh003mesh" geometry={nodes.Wolf3D_Head_Custom_Wolf3D_head_custom_mesh003mesh.geometry} material={nodes.Wolf3D_Head_Custom_Wolf3D_head_custom_mesh003mesh.material} skeleton={nodes.Wolf3D_Head_Custom_Wolf3D_head_custom_mesh003mesh.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom_Wolf3D_outfit_bottom_mesh009mesh" geometry={nodes.Wolf3D_Outfit_Bottom_Wolf3D_outfit_bottom_mesh009mesh.geometry} material={nodes.Wolf3D_Outfit_Bottom_Wolf3D_outfit_bottom_mesh009mesh.material} skeleton={nodes.Wolf3D_Outfit_Bottom_Wolf3D_outfit_bottom_mesh009mesh.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear_Retopo_Wolf3D_outfit_footwear_me_a330ea9" geometry={nodes.Wolf3D_Outfit_Footwear_Retopo_Wolf3D_outfit_footwear_me_a330ea9.geometry} material={nodes.Wolf3D_Outfit_Footwear_Retopo_Wolf3D_outfit_footwear_me_a330ea9.material} skeleton={nodes.Wolf3D_Outfit_Footwear_Retopo_Wolf3D_outfit_footwear_me_a330ea9.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top_Wolf3D_outfit_top_mesh013mesh" geometry={nodes.Wolf3D_Outfit_Top_Wolf3D_outfit_top_mesh013mesh.geometry} material={nodes.Wolf3D_Outfit_Top_Wolf3D_outfit_top_mesh013mesh.material} skeleton={nodes.Wolf3D_Outfit_Top_Wolf3D_outfit_top_mesh013mesh.skeleton} />
        </group>
        <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={22.9} position={[-0.69, 1.35, 3.39]} rotation={[0.03, -0.21, 0.01]} />
      </group>
    </group>
  )
}

useGLTF.preload('/ScottApe_2-transformed.glb')
